name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger

env:
  TF_VERSION: "1.5.0"

permissions:
  id-token: write
  contents: read

jobs:
  drift-detection:
    name: Drift Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      working-directory: ./infra/tf-app
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Plan
      working-directory: ./infra/tf-app
      run: terraform plan -detailed-exitcode
      continue-on-error: true
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Check for Drift
      run: |
        if [ $? -eq 2 ]; then
          echo "❌ Infrastructure drift detected!"
          echo "Please review the Terraform plan above and apply changes if needed."
          exit 1
        elif [ $? -eq 0 ]; then
          echo "✅ No infrastructure drift detected."
        else
          echo "⚠️ Terraform plan failed. Please check the logs above."
          exit 1
        fi
      working-directory: ./infra/tf-app 